import { supabase } from "@/integrations/supabase/client";

export type HeroSlide = {
  id: string;
  slug: string;
  kicker: string;
  title: string;
  subtitle: string;
  cta_primary: string;
  cta_secondary: string;
  cta_link: string;
  gradient: string;
  icon_name: string;
  accent: string;
  position: number;
  visible: boolean;
  published_at: string | null;
  unpublish_at: string | null;
};

/** Default slides used when no hero_slides content is available. */
export const FALLBACK_HERO_SLIDES: HeroSlide[] = [
  {
    id: "hero-1",
    slug: "12-000-software-solutions",
    kicker: "Marketplace",
    title: "12,000+ Software Solutions",
    subtitle: "One Marketplace. Every Business Need.",
    cta_primary: "Browse Products",
    cta_secondary: "Watch Live Demo",
    cta_link: "/demos/public",
    gradient: "from-[#0b1a30] via-[#12325c] to-[#0a1526]",
    icon_name: "Boxes",
    accent: "text-cyan-300",
    position: 0,
    visible: true,
    published_at: null,
    unpublish_at: null,
  },
  {
    id: "hero-2",
    slug: "business-enterprise-solutions",
    kicker: "Enterprise Ready",
    title: "Business & Enterprise Solutions",
    subtitle: "ERP • CRM • HRM • Accounting",
    cta_primary: "Explore Suites",
    cta_secondary: "Watch Live Demo",
    cta_link: "/#Enterprise",
    gradient: "from-[#1a1030] via-[#3b1f6b] to-[#0e0a1e]",
    icon_name: "Crown",
    accent: "text-violet-300",
    position: 1,
    visible: true,
    published_at: null,
    unpublish_at: null,
  },
  {
    id: "hero-3",
    slug: "education-training-solutions",
    kicker: "Education",
    title: "Education & Training Solutions",
    subtitle: "School • College • E-Learning • Coaching",
    cta_primary: "Explore Education",
    cta_secondary: "Watch Live Demo",
    cta_link: "/#Education",
    gradient: "from-[#071b33] via-[#1d4ed8] to-[#0a1526]",
    icon_name: "GraduationCap",
    accent: "text-sky-300",
    position: 2,
    visible: true,
    published_at: null,
    unpublish_at: null,
  },
  {
    id: "hero-4",
    slug: "healthcare-medical-solutions",
    kicker: "Healthcare",
    title: "Healthcare & Medical Solutions",
    subtitle: "Hospital • Clinic • Pharmacy • Laboratory",
    cta_primary: "Explore Healthcare",
    cta_secondary: "Watch Live Demo",
    cta_link: "/#Healthcare",
    gradient: "from-[#2a0a1c] via-[#9d174d] to-[#1a0512]",
    icon_name: "Stethoscope",
    accent: "text-rose-300",
    position: 3,
    visible: true,
    published_at: null,
    unpublish_at: null,
  },
  {
    id: "hero-5",
    slug: "retail-sales-solutions",
    kicker: "Retail & POS",
    title: "Retail & Sales Solutions",
    subtitle: "POS • Retail • Inventory • Billing",
    cta_primary: "Explore Retail",
    cta_secondary: "Watch Live Demo",
    cta_link: "/#Retail%20%26%20POS",
    gradient: "from-[#2a1405] via-[#b45309] to-[#170b02]",
    icon_name: "Store",
    accent: "text-amber-300",
    position: 4,
    visible: true,
    published_at: null,
    unpublish_at: null,
  },
  {
    id: "hero-6",
    slug: "hospitality-food-solutions",
    kicker: "Hospitality",
    title: "Hospitality & Food Solutions",
    subtitle: "Hotel • Restaurant • Cafe • Food Delivery",
    cta_primary: "Explore Hospitality",
    cta_secondary: "Watch Live Demo",
    cta_link: "/#Hospitality",
    gradient: "from-[#2b0f16] via-[#be3455] to-[#180810]",
    icon_name: "Utensils",
    accent: "text-orange-300",
    position: 5,
    visible: true,
    published_at: null,
    unpublish_at: null,
  },
  {
    id: "hero-7",
    slug: "manufacturing-industry-solutions",
    kicker: "Manufacturing",
    title: "Manufacturing & Industry Solutions",
    subtitle: "Factory • Warehouse • Supply Chain • Production",
    cta_primary: "Explore Manufacturing",
    cta_secondary: "Watch Live Demo",
    cta_link: "/#Manufacturing",
    gradient: "from-[#131720] via-[#3f4c63] to-[#0b0e14]",
    icon_name: "Boxes",
    accent: "text-slate-200",
    position: 6,
    visible: true,
    published_at: null,
    unpublish_at: null,
  },
  {
    id: "hero-8",
    slug: "transport-logistics-solutions",
    kicker: "Logistics",
    title: "Transport & Logistics Solutions",
    subtitle: "Logistics • Cargo • Fleet • Transportation",
    cta_primary: "Explore Logistics",
    cta_secondary: "Watch Live Demo",
    cta_link: "/#Logistics",
    gradient: "from-[#04211f] via-[#0f766e] to-[#03130f]",
    icon_name: "Rocket",
    accent: "text-teal-300",
    position: 7,
    visible: true,
    published_at: null,
    unpublish_at: null,
  },
  {
    id: "hero-9",
    slug: "finance-professional-solutions",
    kicker: "Finance",
    title: "Finance & Professional Solutions",
    subtitle: "Finance • Loan • Insurance • Tax",
    cta_primary: "Explore Finance",
    cta_secondary: "Watch Live Demo",
    cta_link: "/#Finance",
    gradient: "from-[#0a2019] via-[#12523c] to-[#07130f]",
    icon_name: "BadgeCheck",
    accent: "text-emerald-300",
    position: 8,
    visible: true,
    published_at: null,
    unpublish_at: null,
  },
  {
    id: "hero-10",
    slug: "property-service-solutions",
    kicker: "Real Estate",
    title: "Property & Service Solutions",
    subtitle: "Real Estate • Society • Facility • Service Management",
    cta_primary: "Explore Property",
    cta_secondary: "Watch Live Demo",
    cta_link: "/#Real%20Estate",
    gradient: "from-[#241a04] via-[#a16207] to-[#140d02]",
    icon_name: "Users",
    accent: "text-yellow-300",
    position: 9,
    visible: true,
    published_at: null,
    unpublish_at: null,
  },
  {
    id: "hero-11",
    slug: "lifetime-software-only-249",
    kicker: "Lifetime Deal",
    title: "Lifetime Software — Only $249",
    subtitle: "One Payment. Lifetime Ownership.",
    cta_primary: "Buy Lifetime",
    cta_secondary: "Watch Live Demo",
    cta_link: "/demos/public",
    gradient: "from-[#231603] via-[#c2760a] to-[#130c02]",
    icon_name: "Crown",
    accent: "text-amber-300",
    position: 10,
    visible: true,
    published_at: null,
    unpublish_at: null,
  },
  {
    id: "hero-12",
    slug: "no-hidden-charges",
    kicker: "Transparent Pricing",
    title: "No Hidden Charges",
    subtitle: "100% Transparent Pricing.",
    cta_primary: "See Pricing",
    cta_secondary: "Watch Live Demo",
    cta_link: "/#pricing",
    gradient: "from-[#052018] via-[#0f766e] to-[#04120e]",
    icon_name: "BadgeCheck",
    accent: "text-emerald-300",
    position: 11,
    visible: true,
    published_at: null,
    unpublish_at: null,
  },
  {
    id: "hero-13",
    slug: "no-advance-payment",
    kicker: "Trust First",
    title: "No Advance Payment",
    subtitle: "Business Built on Trust.",
    cta_primary: "Start Risk-Free",
    cta_secondary: "Watch Live Demo",
    cta_link: "/demos/public",
    gradient: "from-[#04202b] via-[#0e7490] to-[#03131a]",
    icon_name: "ShieldCheck",
    accent: "text-cyan-300",
    position: 12,
    visible: true,
    published_at: null,
    unpublish_at: null,
  },
  {
    id: "hero-14",
    slug: "24-7-technical-support",
    kicker: "Global Support",
    title: "24/7 Technical Support",
    subtitle: "Always Ready to Help.",
    cta_primary: "Contact Support",
    cta_secondary: "Watch Live Demo",
    cta_link: "/#Support",
    gradient: "from-[#08182e] via-[#1e40af] to-[#050d1a]",
    icon_name: "Globe2",
    accent: "text-sky-300",
    position: 13,
    visible: true,
    published_at: null,
    unpublish_at: null,
  },
  {
    id: "hero-15",
    slug: "buy-sell-resell-franchise",
    kicker: "Opportunities",
    title: "Buy • Sell • Resell • Franchise",
    subtitle: "Multiple Business Opportunities.",
    cta_primary: "Explore Options",
    cta_secondary: "Watch Live Demo",
    cta_link: "/apply",
    gradient: "from-[#22052a] via-[#a21caf] to-[#130317]",
    icon_name: "Rocket",
    accent: "text-fuchsia-300",
    position: 14,
    visible: true,
    published_at: null,
    unpublish_at: null,
  },
  {
    id: "hero-16",
    slug: "reseller-distributor-franchise-influence",
    kicker: "Partner Program",
    title: "Reseller • Distributor • Franchise • Influencer",
    subtitle: "Grow with Software Vala.",
    cta_primary: "Become a Partner",
    cta_secondary: "Watch Live Demo",
    cta_link: "/apply",
    gradient: "from-[#160a2c] via-[#6d28d9] to-[#0c0619]",
    icon_name: "Users",
    accent: "text-violet-300",
    position: 15,
    visible: true,
    published_at: null,
    unpublish_at: null,
  },
  {
    id: "hero-17",
    slug: "demo-videos-tutorials",
    kicker: "Live Demos",
    title: "Demo Videos & Tutorials",
    subtitle: "Show. Explain. Sell.",
    cta_primary: "Watch Demos",
    cta_secondary: "Browse Products",
    cta_link: "/demos/public",
    gradient: "from-[#2a0713] via-[#be123c] to-[#16040a]",
    icon_name: "Play",
    accent: "text-rose-300",
    position: 16,
    visible: true,
    published_at: null,
    unpublish_at: null,
  },
  {
    id: "hero-18",
    slug: "don-t-build-software-from-scratch",
    kicker: "Ready to Deploy",
    title: "Don’t Build Software From Scratch",
    subtitle: "Start with Ready-Made Solutions.",
    cta_primary: "Get Started",
    cta_secondary: "Watch Live Demo",
    cta_link: "/demos/public",
    gradient: "from-[#1f1a03] via-[#ca8a04] to-[#120f02]",
    icon_name: "Zap",
    accent: "text-yellow-300",
    position: 17,
    visible: true,
    published_at: null,
    unpublish_at: null,
  },
  {
    id: "hero-19",
    slug: "80-business-categories",
    kicker: "Categories",
    title: "80+ Business Categories",
    subtitle: "Everything Your Business Needs.",
    cta_primary: "Browse Categories",
    cta_secondary: "Watch Live Demo",
    cta_link: "/#all",
    gradient: "from-[#04211d] via-[#0d9488] to-[#031311]",
    icon_name: "Boxes",
    accent: "text-teal-300",
    position: 18,
    visible: true,
    published_at: null,
    unpublish_at: null,
  },
  {
    id: "hero-20",
    slug: "software-vala-the-name-of-trust",
    kicker: "The Name of Trust",
    title: "Software Vala — The Name of Trust",
    subtitle: "One Marketplace. Endless Business Opportunities.",
    cta_primary: "Browse Products",
    cta_secondary: "Watch Live Demo",
    cta_link: "/demos/public",
    gradient: "from-[#0b1a30] via-[#12325c] to-[#0a1526]",
    icon_name: "Sparkles",
    accent: "text-cyan-300",
    position: 19,
    visible: true,
    published_at: null,
    unpublish_at: null,
  },
];

/** Public hero slides for the homepage carousel (falls back to defaults). */
export async function listHeroSlidesPublic(): Promise<HeroSlide[]> {
  try {
    const { data, error } = await (supabase as any)
      .from("hero_slides")
      .select("*")
      .order("position", { ascending: true });
    if (error) return FALLBACK_HERO_SLIDES;
    const rows = (data ?? []) as HeroSlide[];
    return rows.length ? rows : FALLBACK_HERO_SLIDES;
  } catch {
    return FALLBACK_HERO_SLIDES;
  }
}
