/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CreatorManagerRouteImport } from './routes/creator-manager'
import { Route as FranchiseManagerRouteImport } from './routes/franchise-manager'
import { Route as InfluencerManagerRouteImport } from './routes/influencer-manager'
import { Route as ResellerManagerRouteImport } from './routes/reseller-manager'
import { Route as ApiChatRouteImport } from './routes/api/chat'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatorManagerRoute = CreatorManagerRouteImport.update({
  id: '/creator-manager',
  path: '/creator-manager',
  getParentRoute: () => rootRouteImport,
} as any)
const FranchiseManagerRoute = FranchiseManagerRouteImport.update({
  id: '/franchise-manager',
  path: '/franchise-manager',
  getParentRoute: () => rootRouteImport,
} as any)
const InfluencerManagerRoute = InfluencerManagerRouteImport.update({
  id: '/influencer-manager',
  path: '/influencer-manager',
  getParentRoute: () => rootRouteImport,
} as any)
const ResellerManagerRoute = ResellerManagerRouteImport.update({
  id: '/reseller-manager',
  path: '/reseller-manager',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/creator-manager': typeof CreatorManagerRoute
  '/franchise-manager': typeof FranchiseManagerRoute
  '/influencer-manager': typeof InfluencerManagerRoute
  '/reseller-manager': typeof ResellerManagerRoute
  '/api/chat': typeof ApiChatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/creator-manager': typeof CreatorManagerRoute
  '/franchise-manager': typeof FranchiseManagerRoute
  '/influencer-manager': typeof InfluencerManagerRoute
  '/reseller-manager': typeof ResellerManagerRoute
  '/api/chat': typeof ApiChatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/creator-manager': typeof CreatorManagerRoute
  '/franchise-manager': typeof FranchiseManagerRoute
  '/influencer-manager': typeof InfluencerManagerRoute
  '/reseller-manager': typeof ResellerManagerRoute
  '/api/chat': typeof ApiChatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/creator-manager'
    | '/franchise-manager'
    | '/influencer-manager'
    | '/reseller-manager'
    | '/api/chat'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/creator-manager'
    | '/franchise-manager'
    | '/influencer-manager'
    | '/reseller-manager'
    | '/api/chat'
  id:
    | '__root__'
    | '/'
    | '/creator-manager'
    | '/franchise-manager'
    | '/influencer-manager'
    | '/reseller-manager'
    | '/api/chat'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CreatorManagerRoute: typeof CreatorManagerRoute
  FranchiseManagerRoute: typeof FranchiseManagerRoute
  InfluencerManagerRoute: typeof InfluencerManagerRoute
  ResellerManagerRoute: typeof ResellerManagerRoute
  ApiChatRoute: typeof ApiChatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creator-manager': {
      id: '/creator-manager'
      path: '/creator-manager'
      fullPath: '/creator-manager'
      preLoaderRoute: typeof CreatorManagerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/franchise-manager': {
      id: '/franchise-manager'
      path: '/franchise-manager'
      fullPath: '/franchise-manager'
      preLoaderRoute: typeof FranchiseManagerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/influencer-manager': {
      id: '/influencer-manager'
      path: '/influencer-manager'
      fullPath: '/influencer-manager'
      preLoaderRoute: typeof InfluencerManagerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reseller-manager': {
      id: '/reseller-manager'
      path: '/reseller-manager'
      fullPath: '/reseller-manager'
      preLoaderRoute: typeof ResellerManagerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CreatorManagerRoute: CreatorManagerRoute,
  FranchiseManagerRoute: FranchiseManagerRoute,
  InfluencerManagerRoute: InfluencerManagerRoute,
  ResellerManagerRoute: ResellerManagerRoute,
  ApiChatRoute: ApiChatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
